export const projects = [
    {title: "Agenddo", 
    descriptionEs: "Web app que da a los profesionales y establecimientos que se registran una plataforma desde donde llevar el control de su actividad, más una tienda online para que sus clientes puedan reservar turnos.", 
    descriptionEn: "Web that gives registered professionals and establishments a platform from which to administrate their activity, plus an online store so that their clients can book appointments.", 
    technologies: [],
    page: "https://app.agenddo.com/", repo: "", imgs: ["../src/images/Inicio.png", "../src/images/AgregarSuc.png", "../src/images/VistaTurnosDesk.png", "../src/images/Métricas.png", "../src/images/Planes.png", "../src/images/Extras.png", "../src/images/PacienteMob1.png", "../src/images/PacienteMob2.png", "../src/images/CapturaTienda.png", "../src/images/CapturaAgendando.png"]}, 
    {title: "SnorInn-App", 
    descriptionEs: "Web app que conecta a aquellos con un espacio disponible para hospedar personas, y aquellas personas que quieren encontrar un lugar para descansar.", 
    descriptionEn: "Web app that connects those with a space available to host people, and those who want to find a place to rest.",
    technologies: [], 
    page: "https://snor-inn.vercel.app/", repo: "https://github.com/MarquezE92/SnorInn-App", imgs: ["../src/images/SnorInn.png", "../src/images/habitaciones.png", "../src/images/detalleRoom.png", "../src/images/review.png"]}, 
    {title: "Pokemon-App", 
    descriptionEs: "Web App que te permite explorar los 40 primeros pokémons y crear los tuyos.", 
    descriptionEn: "Web App that allows you to explore the first 40 pokémons and create your own.",
    technologies: [], 
    page: "https://pi-pokemon-bice.vercel.app/home", repo: "https://github.com/MarquezE92/PI-Pokemon",  imgs: ["../src/images/Landing.png", "../src/images/home.png", "../src/images/form.png", "../src/images/cards.png", "../src/images/Detail.png",]}]